export const BOAT_BY_OWNER_REQUEST = 'BOAT_BY_OWNER_REQUEST'; 
export const BOAT_BY_OWNER_SUCCESS = 'BOAT_BY_OWNER_SUCCESS'; 
export const BOAT_BY_OWNER_FAIL = 'BOAT_BY_OWNER_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS'; 