export const CREATE_RESERVATION_REQUEST = 'CREATE_RESERVATION_REQUEST'
export const CREATE_RESERVATION_SUCCESS = 'CREATE_RESERVATION_SUCCESS'
export const CREATE_RESERVATION_FAIL = 'CREATE_RESERVATION_FAIL'

export const BOOKER_RESERVATIONS_REQUEST = 'BOOKER_RESERVATIONS_REQUEST'
export const BOOKER_RESERVATIONS_SUCCESS = 'BOOKER_RESERVATIONS_SUCCESS'
export const BOOKER_RESERVATIONS_FAIL = 'BOOKER_RESERVATIONS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'