export const NEXT_TRIPS_BY_BOAT_REQUEST = 'NEXT_TRIPS_BY_BOAT_REQUEST'
export const NEXT_TRIPS_BY_BOAT_SUCCESS = 'NEXT_TRIPS_BY_BOAT_SUCCESS'
export const NEXT_TRIPS_BY_BOAT_FAIL = 'NEXT_TRIPS_BY_BOAT_FAIL'

export const TRIP_DETAILS_REQUEST = 'TRIP_DETAILS_REQUEST';
export const TRIP_DETAILS_SUCCESS = 'TRIP_DETAILS_SUCCESS';
export const TRIP_DETAILS_FAIL = 'TRIP_DETAILS_FAIL';

export const TRIPS_BY_BOAT_REQUEST = 'TRIPS_BY_BOAT_REQUEST'
export const TRIPS_BY_BOAT_SUCCESS = 'TRIPS_BY_BOAT_SUCCESS'
export const TRIPS_BY_BOAT_FAIL = 'TRIPS_BY_BOAT_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS';