export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_RESET = 'UPDATE_PASSWORD_RESET'
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL'

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

export const REGISTER_BOOKER_REQUEST = 'REGISTER_BOOKER_REQUEST'
export const REGISTER_BOOKER_SUCCESS = 'REGISTER_BOOKER_SUCCESS'
export const REGISTER_BOOKER_FAIL = 'REGISTER_BOOKER_FAIL'

export const DELETE_BOOKER_REQUEST = 'DELETE_BOOKER_REQUEST'
export const DELETE_BOOKER_SUCCESS = 'DELETE_BOOKER_SUCCESS'
export const DELETE_BOOKER_RESET = 'DELETE_BOOKER_RESET'
export const DELETE_BOOKER_FAIL = 'DELETE_BOOKER_FAIL'

export const ALL_BOOKERS_REQUEST = 'ALL_BOOKERS_REQUEST'
export const ALL_BOOKERS_SUCCESS = 'ALL_BOOKERS_SUCCESS'
export const ALL_BOOKERS_FAIL = 'ALL_BOOKERS_FAIL'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'